stages:
  - sync

sync_job:
  stage: sync
  tags:
    - migrasi_mysql
  script:
    - echo "Mulai sync job"
    - mkdir -p logs
    - bash /home/user/Projects/sync_migrasi.sh > logs/rsync.log 2>&1
    - echo "Selesai"
    - echo "Log file summary:"
    - tail -10 logs/rsync.log
  artifacts:
    paths:
      - logs/rsync.log
    expire_in: 1 week
  after_script:
    - echo "Job completed, artifacts should be available"
